name: Release workflow
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and create release
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-gnu
      env:
        RUSTFLAGS: "-C target-feature=+crt-static"

    - name: Create release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          target/x86_64-unknown-linux-gnu/release/robots
          LICENSE
          README.md
        generate_release_notes: true
