name: Release workflow
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-gnu
      env:
        RUSTFLAGS: "-C target-feature=+crt-static"
    - name: Create release
      id: create_release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          target/x86_64-unknown-linux-gnu/release/robots
          LICENSE
          README.md
        generate_release_notes: true
