name: Test build and cargo fmt check
on:
  pull_request:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    # - name: Format check
    #   run: cargo fmt --check
    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-gnu
      env:
        RUSTFLAGS: "-C target-feature=+crt-static"
